name: Build and Release

on:
 push:
    branches:
      - main

jobs:
 build:
    runs-on: ubuntu-latest

    env:
     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.x'

    - name: Clone WVCore
      run: git clone https://github.com/nilaoda/WVCore

    - name: Clone WVCore.Server
      run: git clone https://github.com/nilaoda/WVCore.Server

    - name: Build WVCore.Server
      run: |
        cd WVCore.Server
        rm Directory.Build.props
        dotnet publish -r win-x64 -c Release
        dotnet publish -r win-x86 -c Release
        dotnet publish -r win-arm64 -c Release
        dotnet publish -r linux-x64 -c Release
        dotnet publish -r linux-musl-x64 -c Release
        dotnet publish -r linux-musl-arm64 -c Release
        dotnet publish -r linux-arm -c Release
        dotnet publish -r linux-arm64 -c Release
        dotnet publish -r linux-bionic-arm64 -c Release
        dotnet publish -r osx-x64 -c Release
        dotnet publish -r osx-arm64 -c Release
        readlink -f ./

    - name: Create Release
      run: |
        gh release create ${{ github.run_id }} -R FoxRefire/WVCore.Server

    - name: Upload Release
      run: |
        ls -R
        echo ==DEBUG==
        zip ./bin/Release/net7.0/win-x64/publish/WVCore.Server-win-x64.zip ./bin/Release/net7.0/win-x64/publish/*
        gh release upload ${{ github.run_id }} ./bin/Release/net7.0/win-x64/publish/WVCore.Server-win-x64.zip -R FoxRefire/WVCore.Server

        zip ./bin/Release/net7.0/win-x86/publish/WVCore.Server-win-x86.zip ./bin/Release/net7.0/win-x86/publish/*
        gh release upload ${{ github.run_id }} ./bin/Release/net7.0/win-x86/publish/WVCore.Server-win-x86.zip -R FoxRefire/WVCore.Server

        zip ./bin/Release/net7.0/win-arm64/publish/WVCore.Server-win-arm64.zip ./bin/Release/net7.0/win-arm64/publish/*
        gh release upload ${{ github.run_id }} ./bin/Release/net7.0/win-arm64/publish/WVCore.Server-win-arm64.zip -R FoxRefire/WVCore.Server

        zip ./bin/Release/net7.0/linux-x64/publish/WVCore.Server-linux-x64.zip ./bin/Release/net7.0/linux-x64/publish/*
        gh release upload ${{ github.run_id }} ./bin/Release/net7.0/linux-x64/publish/WVCore.Server-linux-x64.zip -R FoxRefire/WVCore.Server

        zip ./bin/Release/net7.0/linux-musl-x64/publish/WVCore.Server-linux-musl-x64.zip ./bin/Release/net7.0/linux-musl-x64/publish/*
        gh release upload ${{ github.run_id }} ./bin/Release/net7.0/linux-musl-x64/publish/WVCore.Server-linux-musl-x64.zip -R FoxRefire/WVCore.Server

        zip ./bin/Release/net7.0/linux-musl-arm64/publish/WVCore.Server-linux-musl-arm64.zip ./bin/Release/net7.0/linux-musl-arm64/publish/*
        gh release upload ${{ github.run_id }} ./bin/Release/net7.0/linux-musl-arm64/publish/WVCore.Server-linux-musl-arm64.zip -R FoxRefire/WVCore.Server

        zip ./bin/Release/net7.0/linux-arm/publish/WVCore.Server-linux-arm.zip ./bin/Release/net7.0/linux-arm/publish/*
        gh release upload ${{ github.run_id }} ./bin/Release/net7.0/linux-arm/publish/WVCore.Server-linux-arm.zip -R FoxRefire/WVCore.Server

        zip ./bin/Release/net7.0/linux-arm64/publish/WVCore.Server-linux-arm64.zip ./bin/Release/net7.0/linux-arm64/publish/*
        gh release upload ${{ github.run_id }} ./bin/Release/net7.0/linux-arm64/publish/WVCore.Server-linux-arm64.zip -R FoxRefire/WVCore.Server

        zip ./bin/Release/net7.0/linux-bionic-arm64/publish/WVCore.Server-linux-bionic-arm64.zip ./bin/Release/net7.0/linux-bionic-arm64/publish/*
        gh release upload ${{ github.run_id }} ./bin/Release/net7.0/linux-bionic-arm64/publish/WVCore.Server-linux-bionic-arm64.zip -R FoxRefire/WVCore.Server

        zip ./bin/Release/net7.0/osx-x64/publish/WVCore.Server-osx-x64.zip ./bin/Release/net7.0/osx-x64/publish/*
        gh release upload ${{ github.run_id }} ./bin/Release/net7.0/osx-x64/publish/WVCore.Server-osx-x64.zip -R FoxRefire/WVCore.Server

        zip ./bin/Release/net7.0/osx-arm64/publish/WVCore.Server-osx-arm64.zip ./bin/Release/net7.0/osx-arm64/publish/*
        gh release upload ${{ github.run_id }} ./bin/Release/net7.0/osx-arm64/publish/WVCore.Server-osx-arm64.zip -R FoxRefire/WVCore.Server
        
        
        

